#!/usr/bin/env python3
"""
Generate all language translation files for RagnaController localization system
Creates translations for 16 languages with proper translations
"""

import json
import os

# Project root
PROJECT_ROOT = "/mnt/c/RagnaController/src/RagnaController/Locales"

# Load English base file
with open(os.path.join(PROJECT_ROOT, "en.json"), 'r', encoding='utf-8') as f:
    en_keys = json.load(f)

print("=" * 70)
print("RAGNACONTROLLER LOCALIZATION - GENERATING LANGUAGE FILES")
print("=" * 70)
print()

# Language codes and their display names
LANGUAGES = {
    "de": "Deutsch (German)",
    "fr": "Français (French)",
    "it": "Italiano (Italian)",
    "es": "Español (Spanish)",
    "pt": "Português (Portuguese)",
    "nl": "Nederlands (Dutch)",
    "pl": "Polski (Polish)",
    "ru": "Русский (Russian)",
    "sv": "Svenska (Swedish)",
    "no": "Norsk (Norwegian)",
    "da": "Dansk (Danish)",
    "tl": "Filipino (Tagalog)",
    "ko": "한국어 (Korean)",
    "th": "ภาษาไทย (Thai)",
    "id": "Bahasa Indonesia",
    "zh": "中文 (Chinese)",
}

# Translation function for each language
def translate_de(value):
    """German translation function."""
    translations = {
        "App_Title": "RagnaController",
        "Btn_Play": "SPIELEN",
        "Btn_Play_Desc": "Ragnarok Online starten",
        "Btn_Profiles": "PROFILE",
        "Btn_Settings": "EINSTELLUNGEN",
        "Btn_Community": "GEMEINSCHAFT",
        "Btn_Exit": "VERLASSEN",
        "Settings_Language": "Sprache",
        "Settings_Save": "SPEICHERN & SCHLIESSEN",
        "Status_Running": "LAUFEND",
        "Status_Paused": "PAUSIERT",
        "Status_NoController": "KEIN CONTROLLER",
        "Toast_ProfileLoaded": "Profil geladen:",
        "Window_Title": "RagnaController",
        "Device_Label": "Gerät",
        "ActiveProfileText": "Aktives Profil",
        "ControllerStatusText": "Controller-Status",
        "Header_Ragna": "⚔ RAGNA CONTROLLER",
        "Footer_ControllerHints": "D-Pad navigieren / A auswählen / B zurück / Start zum Spiel",
        "Settings_Title": "Einstellungen",
        "Settings_Deadzone": "TOTZONE",
        "Settings_Turbo": "TURBO",
        "Settings_Gyro": "GYRO",
        "Settings_SaveBtn": "SPEICHERN",
        "Settings_ResetBtn": "ZURÜCKSETZEN",
        "Settings_CloseBtn": "SCHLIESSEN",
        "Settings_DeadzoneValue": "Totzone: {0}",
        "Settings_TurboDelay": "Turbo-Verzögerung: {0}ms",
        "Settings_GyroSensitivity": "Gyro-Empfindlichkeit: {0}x",
        "ButtonRemap_Title": "Tastenzuordnung",
        "ButtonRemap_Header": "TASTENZUORDNUNG",
        "ButtonRemap_SelectBtn": "Wählen Sie eine Taste zur Zuordnung",
        "ButtonRemap_SaveBtn": "SPEICHERN",
        "ButtonRemap_CloseBtn": "SCHLIESSEN",
        "ComboEditor_Title": "Kombinations-Editor",
        "ComboEditor_Header": "KOMBINATIONSENGINE EDITOR",
        "ComboEditor_EnableCheck": "Kombination aktiv",
        "ComboEditor_CloseBtn": "✕",
        "ComboEditor_SelectClassTemplate": "Klassen-Vorlage auswählen",
        "ComboEditor_DelaysTooltip": "Verzögerungen zwischen Aktionen",
        "ComboEditor_PreRenewalBtn": "VOR-VERNEUERUNG",
        "ComboEditor_RenewalBtn": "VERNEUERUNG",
        "ComboEditor_AddStepTooltip": "Fügen Sie einen neuen Schritt zur Kombination hinzu",
        "ComboEditor_RemoveLastTooltip": "Entfernen Sie den letzten Schritt",
        "ComboEditor_TriggerHint": "Auslöser: Ordnen Sie eine Taste zu 'Klassen-Kombination' und HALTEN Sie sie.",
        "ComboEditor_SaveComboBtn": "KOMBINATION SPEICHERN",
        "ComboEditor_CancelBtn": "Abbrechen",
        "Community_Title": "Gemeinschaftsprofile",
        "Community_Header": "GEMEINSCHAFTSHUB",
        "Community_CloseBtn": "✕",
        "Community_SearchPlaceholder": "Profile suchen...",
        "Community_RefreshBtn": "↻ Aktualisieren",
        "Community_DownloadBtn": "↓ HERUNTERLADEN",
        "Community_LoadingText": "Gemeinschaftsprofile werden geladen...",
        "Community_ErrorText": "Laden fehlgeschlagen.",
        "Community_RetryBtn": "Erneut versuchen",
        "DaisyWheel_Title": "Daisy Wheel",
        "DaisyWheel_Hint": "L3 = ⌫   R3 = Leertaste   / Start = Senden   B = Abbrechen",
        "Handheld_Play_Tooltip": "Spiel starten",
        "Handheld_Profiles_Tooltip": "Profilverwaltung",
        "Handheld_Overlay_Tooltip": "Overlay umschalten",
        "Handheld_Settings_Tooltip": "Einstellungen",
        "Handheld_Community_Tooltip": "Gemeinschaftshub",
        "Handheld_Exit_Tooltip": "Anwendung beenden",
        "InGame_Title": "RagnaController Overlay",
        "InGame_LayerLabel": "SCHICHT",
        "InGame_BaseLayer": "BASIS",
        "InGame_LayerTooltip": "Aktuelle Schicht-Anzeige: BASIS / L1+ / R1+ / L2+ / R2+",
        "InGame_TrackDotTooltip": "Fensterverfolgungsanzeige",
        "InGame_IdleState": "IDLE",
        "InGame_StateTooltip": "Aktueller Kampfzustand",
        "MacroEditor_Title": "Makro-Editor",
        "MacroEditor_Header": "MAKRO EDITOR",
        "MacroEditor_InfoText": "Bearbeiten Sie Makroschritte und Timing",
        "MacroEditor_NameLabel": "NAME:",
        "MacroEditor_LoopsLabel": "LOOPS:",
        "MacroEditor_DurationLabel": "DAUER: {0}ms",
        "MacroEditor_AddStepBtn": "+ Schritt hinzufügen",
        "MacroEditor_RemoveLastBtn": "- Letzten entfernen",
        "MacroEditor_SpeedUpBtn": "Beschleunigen (×2)",
        "MacroEditor_SlowDownBtn": "Verlangsamen (×2)",
        "MacroEditor_OptimizeBtn": "Optimieren",
        "MacroEditor_PreviewBtn": "Vorschau",
        "MacroEditor_SaveChangesBtn": "ÄNDERUNGEN SPEICHERN",
        "MacroEditor_CancelBtn": "ABBRECHEN",
        "MacroRecorder_Title": "Makro-Recorder",
        "MacroRecorder_Header": "MAKRO RECORDER",
        "MacroRecorder_NameLabel": "MAKRONAME",
        "MacroRecorder_DefaultName": "Unbenanntes Makro",
        "MacroRecorder_RecordBtn": "● AUFNEHMEN",
        "MacroRecorder_StopBtn": "■ STOPPEN",
        "MacroRecorder_ClearBtn": "🗑 LÖSCHEN",
        "MacroRecorder_HintText": "Drücken Sie Aufnehmen und dann Ihre Tasten.",
        "MacroRecorder_EditBtn": "✏ Gespeichertes Makro bearbeiten",
        "MacroRecorder_SaveBtn": "MAKRO SPEICHERN",
        "MacroTimeline_Title": "Makro-Zeitleiste",
        "MacroTimeline_Header": "MAKRO ZEITLEISTE",
        "MacroTimeline_Subtitle": "Laden Sie ein Makro, um sein Timing zu visualisieren",
        "MacroTimeline_LoadTooltip": "Makrodatei laden",
        "MacroTimeline_PlayTooltip": "Makroz Zeitleiste abspielen",
        "MacroTimeline_ZoomTooltip": "Makroz Zeitleisten-Zoomstufe anpassen",
        "MacroTimeline_KeyTooltip": "Tastendruckereignis",
        "MacroTimeline_ClickTooltip": "Mausklickereignis",
        "MacroTimeline_RClickTooltip": "Rechtsklickereignis",
        "MacroTimeline_DelayTooltip": "Verzögerungsereignis",
        "MacroTimeline_TotalDurationTooltip": "Gesamte Makrodauer",
        "MacroTimeline_ZoomLabel": "{0}×",
        "MacroTimeline_Legend_Key": "Taste",
        "MacroTimeline_Legend_Click": "Klick",
        "MacroTimeline_Legend_RClick": "R-Klick",
        "MacroTimeline_Legend_Delay": "Verzögerung",
        "MacroTimeline_HoverHint": "Fahren Sie mit der Maus über einen Schritt, um Details anzuzeigen",
        "MacroTimeline_CloseBtn": "Schließen",
        "ProfileLibrary_Title": "Profilbibliothek",
        "ProfileLibrary_Header": "PROFILBIBLIOTHEK",
        "ProfileLibrary_CloseBtn": "✕",
        "ProfileLibrary_AllProfiles": "Alle Profile",
        "ProfileLibrary_BuiltInOnly": "Nur Eingebaut",
        "ProfileLibrary_CustomOnly": "Nur Benutzerdefiniert",
        "ProfileLibrary_Melee": "Kampf",
        "ProfileLibrary_Ranged": "Reichweite",
        "ProfileLibrary_Mage": "Magier",
        "ProfileLibrary_Support": "Support",
        "ProfileLibrary_CountLabel": "{0} Profile",
        "ProfileLibrary_LoadBtn": "Laden",
        "ProfileLibrary_ExportBtn": "Exportieren",
        "ProfileLibrary_ShareBtn": "↑ TEILEN",
        "ProfileLibrary_DeleteBtn": "Löschen",
        "ProfileLibrary_StatusText": "",
        "ProfileLibrary_NewProfileBtn": "Neues Profil",
        "ProfileLibrary_ImportBtn": "Importieren",
        "ProfileLibrary_ShareCodePlaceholder": "Geben Sie einen Teilcode ein (z. B. GX-A3F9) und klicken Sie auf ↓ Herunterladen",
        "ProfileLibrary_DownloadBtn": "↓ Herunterladen",
        "ProfileWizard_Title": "Assistent",
        "ProfileWizard_Header": "PROFILASSISTENT",
        "ProfileWizard_NameLabel": "PROFILNAME",
        "ProfileWizard_ClassLabel": "KLASSE",
        "ProfileWizard_Melee": "Kampf",
        "ProfileWizard_Mage": "Magier",
        "ProfileWizard_Ranged": "Reichweite",
        "ProfileWizard_Support": "Support",
        "ProfileWizard_CombatEngines": "KAMPFENGINE",
        "ProfileWizard_EnableAutoTarget": "Auto-Ziel aktivieren",
        "ProfileWizard_EnableKiteEngine": "Kite-Engine aktivieren",
        "ProfileWizard_EnableMageSystem": "Mage-System aktivieren",
        "ProfileWizard_EnableSupportMode": "Support-Modus aktivieren",
        "ProfileWizard_QuickKeys": "Schnelltasten",
        "ProfileWizard_AButton": "A:",
        "ProfileWizard_BButton": "B:",
        "ProfileWizard_XButton": "X:",
        "ProfileWizard_YButton": "Y:",
        "ProfileWizard_Review": "ÜBERSICHT",
        "ProfileWizard_ReviewMessage": "Das Profil wird mit Standard-Bewegungseinstellungen erstellt. Sie können alles später anpassen.",
        "ProfileWizard_BackBtn": "ZURÜCK",
        "ProfileWizard_NextBtn": "WEITER",
        "RadialMenu_Title": "Radialmenü",
        "RadialMenu_SelectItemText": "ELEMENT AUSWÄHLEN",
        "RadialMenu_SelectItemTooltip": "Wählen Sie eine Aktion aus dem radialen Menü aus",
        "RadialMenu_ExecuteText": "Triggern loslassen, um zu verwenden",
        "RadialMenu_ExecuteTooltip": "Ausgewählte Aktion ausführen",
        "RadialSetup_Title": "Radialmenü-Einrichtung",
        "RadialSetup_Header": "RADIALMENÜEINRICHTUNG",
        "RadialSetup_Hint": "Auslöser: LT + RT gleichzeitig halten → Ziel mit rechtem Stick anpeilen → Triggern loslassen, um auszuführen.",
        "RadialSetup_Column_DisplayName": "ANZEIGENAME",
        "RadialSetup_Column_CommandChat": "BEBEHLEN / CHAT",
        "RadialSetup_Column_KeyBinding": "TASTENZUORDNUNG",
        "RadialSetup_Column_Emotes": "EMOTES",
        "RadialSetup_FooterHint": "Leer lassen, um einen Slot zu deaktivieren. 8 Slots = 8 Richtungen.",
        "RadialSetup_SaveBtn": "RADIAL SPEICHERN",
        "RadialMenuGallery_Title": "EMOTE AUSWÄHLEN",
        "RadialMenuGallery_CloseBtn": "✕",
        "RadialMenuGallery_EmoteStatus": "Emoji-Fallback aktiv",
        "RadialMenuGallery_DownloadBtn": "⬇ Von iROWiki herunterladen",
        "AdminWarning_Message": "Wird nicht als Administrator ausgeführt — SendInput kann nicht korrekt funktionieren.",
        "Btn_RestartAsAdmin": "↑ Als Admin neu starten",
        "Btn_RestartAsAdmin_Tooltip": "Anwendung als Administrator neu starten",
        "ClassBadge_Empty": "⚔ –",
        "GameMode_PreRenewal": "VOR-VERNEUERUNG",
        "GameMode_Renewal": "VERNEUERUNG",
        "ControllerName_NoController": "Kein Controller",
        "BatteryLevel_Empty": "–",
        "SettingsWindow_Title": "Einstellungen",
        "SettingsWindow_Header": "ALLGEMEINE EINSTELLUNGEN",
        "Btn_Close_Tooltip": "Einstellungsfenster schließen",
        "Settings_AutoStart": "Engine beim Start automatisch starten",
        "Settings_AutoStart_Tooltip": "Engine automatisch beim Client-Start aktivieren",
        "Settings_Sound": "Klangfeedback aktivieren",
        "Settings_Sound_Tooltip": "Klick- und Skill-Klänge aktivieren",
        "Settings_Rumble": "Controller-Vibration aktivieren",
        "Settings_Rumble_Tooltip": "Controller-Vibration für Feedback aktivieren",
        "Settings_MiniMode": "Im Mini-Modus starten",
        "Settings_MiniMode_Tooltip": "App im Mini-Overlay-Modus (kompakt) starten",
        "Settings_FocusLock": "Engine pausieren, wenn RO im Hintergrund ist",
        "Settings_FocusLock_Tooltip": "Engine pausieren, wenn RO im Hintergrund ist",
        "Settings_FocusLock_Description": "Verhindert unbeabsichtigte Eingaben in Discord oder Browser, wenn der Tab verlassen wird.",
        "Settings_KernelInput": "Hardware-Eingabe verwenden (Anti-Cheat Umgehung)",
        "Settings_KernelInput_Tooltip": "Erfordert Interception-Treiber. Umgeht Gepard/Harmony-Blockaden.",
        "Btn_InstallDriver": "Treiber installieren",
        "Btn_InstallDriver_Tooltip": "Installiert erforderlichen Kernel-Treiber (Neustart erforderlich)",
        "Settings_LogLevel_Label": "LOG-LEVEL",
        "LogLevel_Debug": "Debug",
        "LogLevel_Info": "Info",
        "LogLevel_Warning": "Warnung",
        "LogLevel_Error": "Fehler",
        "Btn_ReportBug": "🐛 Fehler melden / Feature anfordern",
        "Btn_ReportBug_Tooltip": "Öffnet die GitHub Issues-Seite in Ihrem Webbrowser",
        "Lbl_Version_Tooltip": "Aktuelle App-Version",
        "Lbl_SettingsPath_Tooltip": "Einstellungsverzeichnis öffnen (Windows Explorer)",
        "Btn_Reset": "AUF WERKSEINSTELLUNGEN ZURÜCKSETZEN",
        "Btn_Reset_Tooltip": "Alle Einstellungen auf Standardwerte zurücksetzen",
        "Btn_SaveAndClose": "SPEICHERN & SCHLIESSEN",
        "Btn_SaveAndClose_Tooltip": "Einstellungen speichern und Fenster schließen",
        "Window_Remap_Title": "Tastenzuordnung",
        "Window_Remap_Header": "TASTENZUORDNUNG",
        "Layer_Title_1": "SCHICHT 1",
        "Layer_Title_2": "SCHICHT 2",
        "Layer_Title_3": "SCHICHT 3",
        "Layer_Title_4": "SCHICHT 4",
        "Layer_Title_5": "SCHICHT 5",
        "Window_Combo_Title": "Kombinations-Editor",
        "Window_Combo_Header": "KOMBINATIONSENGINE EDITOR",
        "Combo_Slot_Label_1": "SLOT 1",
        "Combo_Slot_Label_2": "SLOT 2",
        "Combo_Slot_Label_3": "SLOT 3",
        "Combo_Slot_Label_4": "SLOT 4",
        "Combo_Slot_Label_5": "SLOT 5",
        "Window_Community_Title": "Gemeinschaftsbrowser",
        "Window_Community_Header": "GEMEINSCHAFTSBROWSER",
        "Search_Community_Placement": "Profile suchen...",
        "Community_NoResults": "Keine übereinstimmenden Profile gefunden",
        "Btn_LoadMore": "WEITERE LADEN",
        "Btn_LoadMore_Tooltip": "Weitere Gemeinschaftsprofile laden",
        "Btn_Close_Community": "GEMEINSCHAFTSCHLIESSEN",
        "Btn_Close_Community_Tooltip": "Gemeinschaftsbrowser schließen",
        "Window_DaisyWheel_Title": "Daisy Wheel",
        "Window_DaisyWheel_Header": "DAISY WHEEL",
        "Window_Handheld_Title": "Handheld-Modus",
        "Window_Handheld_Header": "HANDELD MODE",
        "Window_Overlay_Title": "In-Spiel-Overlay",
        "Window_Overlay_Header": "IN-SPIEL OVERLAY",
        "Btn_ToggleHUD": "HUD UMSCHALTEN",
        "Btn_ToggleHUD_Tooltip": "In-Spiel-HUD-Overlay ein-/ausblenden",
        "Window_Macro_Title": "Makro-Editor",
        "Window_Macro_Header": "MAKRO EDITOR",
        "Window_MacroRecorder_Title": "Makro-Recorder",
        "Window_MacroRecorder_Header": "MAKRO RECORDER",
        "Btn_StartRecording": "AUFNEHMEN STARTEN",
        "Btn_StartRecording_Tooltip": "Aufnahme von Makro-Aktionen starten",
        "Btn_StopRecording": "AUFNAHME STOPPEN",
        "Btn_StopRecording_Tooltip": "Aufnahme stoppen und Makro speichern",
        "Window_Timeline_Title": "Makro-Zeitleiste",
        "Window_Timeline_Header": "MAKRO ZEITLEISTE",
        "Window_Library_Title": "Profilbibliothek",
        "Window_Library_Header": "PROFILBIBLIOTHEK",
        "Window_Wizard_Title": "Assistent",
        "Window_Wizard_Header": "PROFILASSISTENT",
        "Btn_Next": "WEITER",
        "Btn_Next_Tooltip": "Zum nächsten Schritt fortfahren",
        "Btn_Back": "ZURÜCK",
        "Btn_Back_Tooltip": "Zum vorherigen Schritt zurückgehen",
        "Btn_Finish": "BEENDEN",
        "Btn_Finish_Tooltip": "Profilerstellung abschließen",
        "Window_Radial_Title": "Radialmenü-Einrichtung",
        "Window_Radial_Header": "RADIALMENÜEINRICHTUNG",
        "Splash_Loading": "Laden...",
        "Splash_Version": "Version {version}",
    }
    
    return translations.get(key, value)

def translate_fr(value):
    """French translation function."""
    translations = {
        "App_Title": "RagnaController",
        "Btn_Play": "JOUER",
        "Btn_Play_Desc": "Lancer Ragnarok Online",
        "Btn_Profiles": "PROFILS",
        "Btn_Settings": "PARAMÈTRES",
        "Btn_Community": "COMMUNAUTÉ",
        "Btn_Exit": "QUITTER",
        "Settings_Language": "Langue",
        "Settings_Save": "ENREGISTRER & FERMER",
        "Status_Running": "EN COURS",
        "Status_Paused": "MIS EN PAUSE",
        "Status_NoController": "AUCUN CONTRÔLEUR",
        "Toast_ProfileLoaded": "Profil chargé :",
        "Window_Title": "RagnaController",
        "Device_Label": "Périphérique",
        "ActiveProfileText": "Profil actif",
        "ControllerStatusText": "État du contrôleur",
        "Header_Ragna": "⚔ RAGNA CONTROLLER",
        "Footer_ControllerHints": "Navigation D-Pad / A Sélectionner / B Retour / Start Entrer Jeu",
        "Settings_Title": "Paramètres",
        "Settings_Deadzone": "ZONE MORTE",
        "Settings_Turbo": "TURBO",
        "Settings_Gyro": "GYRO",
        "Settings_SaveBtn": "ENREGISTRER",
        "Settings_ResetBtn": "RÉINITIALISER",
        "Settings_CloseBtn": "FERMER",
        "Settings_DeadzoneValue": "Zone morte : {0}",
        "Settings_TurboDelay": "Délai Turbo : {0}ms",
        "Settings_GyroSensitivity": "Sensibilité Gyro : {0}x",
        "ButtonRemap_Title": "Réaffectation des boutons",
        "ButtonRemap_Header": "RÉAFFECTATION DES BOUTONS",
        "ButtonRemap_SelectBtn": "Sélectionnez un bouton à réaffecter",
        "ButtonRemap_SaveBtn": "ENREGISTRER",
        "ButtonRemap_CloseBtn": "FERMER",
        "ComboEditor_Title": "Éditeur de combinaison",
        "ComboEditor_Header": "ÉDITEUR MOTEUR COMBINAISON",
        "ComboEditor_EnableCheck": "Combinaison active",
        "ComboEditor_CloseBtn": "✕",
        "ComboEditor_SelectClassTemplate": "Sélectionner un modèle de classe",
        "ComboEditor_DelaysTooltip": "Délais entre les actions",
        "ComboEditor_PreRenewalBtn": "AVANT-RENOUVELLEMENT",
        "ComboEditor_RenewalBtn": "RENOUVELLEMENT",
        "ComboEditor_AddStepTooltip": "Ajouter une nouvelle étape à la combinaison",
        "ComboEditor_RemoveLastTooltip": "Supprimer la dernière étape",
        "ComboEditor_TriggerHint": "Déclencheur : Associez un bouton à 'Combinaison de classe' et TENEZ-le.",
        "ComboEditor_SaveComboBtn": "ENREGISTRER COMBINAISON",
        "ComboEditor_CancelBtn": "Annuler",
        "Community_Title": "Profil communautaire",
        "Community_Header": "HUB COMMUNAUTAIRE",
        "Community_CloseBtn": "✕",
        "Community_SearchPlaceholder": "Rechercher des profils...",
        "Community_RefreshBtn": "↻ Rafraîchir",
        "Community_DownloadBtn": "↓ TÉLÉCHARGER",
        "Community_LoadingText": "Chargement des profils communautaires...",
        "Community_ErrorText": "Échec du chargement.",
        "Community_RetryBtn": "Réessayer",
        "DaisyWheel_Title": "Daisy Wheel",
        "DaisyWheel_Hint": "L3 = ⌫   R3 = Espace   / Start = Envoyer   B = Annuler",
        "Handheld_Play_Tooltip": "Démarrer le jeu",
        "Handheld_Profiles_Tooltip": "Gestion des profils",
        "Handheld_Overlay_Tooltip": "Basculer l'overlay",
        "Handheld_Settings_Tooltip": "Paramètres",
        "Handheld_Community_Tooltip": "Hub communautaire",
        "Handheld_Exit_Tooltip": "Quitter l'application",
        "InGame_Title": "Overlay RagnaController",
        "InGame_LayerLabel": "COUCHE",
        "InGame_BaseLayer": "BASE",
        "InGame_LayerTooltip": "Affichage couche actuel : BASE / L1+ / R1+ / L2+ / R2+",
        "InGame_TrackDotTooltip": "Indicateur de suivi de fenêtre",
        "InGame_IdleState": "IDLE",
        "InGame_StateTooltip": "État de combat actuel",
        "MacroEditor_Title": "Éditeur de macro",
        "MacroEditor_Header": "ÉDITEUR DE MACRO",
        "MacroEditor_InfoText": "Modifier les étapes et le timing des macros",
        "MacroEditor_NameLabel": "NOM :",
        "MacroEditor_LoopsLabel": "BUCLES :",
        "MacroEditor_DurationLabel": "DURÉE : {0}ms",
        "MacroEditor_AddStepBtn": "+ Ajouter une étape",
        "MacroEditor_RemoveLastBtn": "- Supprimer le dernier",
        "MacroEditor_SpeedUpBtn": "Accélérer (×2)",
        "MacroEditor_SlowDownBtn": "Ralentir (×2)",
        "MacroEditor_OptimizeBtn": "Optimiser",
        "MacroEditor_PreviewBtn": "Aperçu",
        "MacroEditor_SaveChangesBtn": "ENREGISTRER LES MODIFICATIONS",
        "MacroEditor_CancelBtn": "ANNULER",
        "MacroRecorder_Title": "Enregistreur de macro",
        "MacroRecorder_Header": "ENREGISTREUR DE MACRO",
        "MacroRecorder_NameLabel": "NOM DE MACRO",
        "MacroRecorder_DefaultName": "Macro sans nom",
        "MacroRecorder_RecordBtn": "● ENREGISTRER",
        "MacroRecorder_StopBtn": "■ ARRÊTER",
        "MacroRecorder_ClearBtn": "🗑 EFFACER",
        "MacroRecorder_HintText": "Appuyez sur Enregistrer puis sur vos touches.",
        "MacroRecorder_EditBtn": "✏ Modifier la macro enregistrée",
        "MacroRecorder_SaveBtn": "ENREGISTRER MACRO",
        "MacroTimeline_Title": "Chrono de macro",
        "MacroTimeline_Header": "CHRONO DE MACRO",
        "MacroTimeline_Subtitle": "Charger une macro pour visualiser son timing",
        "MacroTimeline_LoadTooltip": "Charger un fichier de macro",
        "MacroTimeline_PlayTooltip": "Lire la chronologie de la macro",
        "MacroTimeline_ZoomTooltip": "Ajuster le niveau de zoom de la chronologie",
        "MacroTimeline_KeyTooltip": "Événement de pression de touche",
        "MacroTimeline_ClickTooltip": "Événement de clic souris",
        "MacroTimeline_RClickTooltip": "Événement de clic droit",
        "MacroTimeline_DelayTooltip": "Événement de délai",
        "MacroTimeline_TotalDurationTooltip": "Durée totale de la macro",
        "MacroTimeline_ZoomLabel": "{0}×",
        "MacroTimeline_Legend_Key": "Touche",
        "MacroTimeline_Legend_Click": "Clic",
        "MacroTimeline_Legend_RClick": "Clic droit",
        "MacroTimeline_Legend_Delay": "Délai",
        "MacroTimeline_HoverHint": "Passer la souris sur une étape pour voir les détails",
        "MacroTimeline_CloseBtn": "Fermer",
        "ProfileLibrary_Title": "Bibliothèque de profils",
        "ProfileLibrary_Header": "BIBLIOTHÈQUE DE PROFILS",
        "ProfileLibrary_CloseBtn": "✕",
        "ProfileLibrary_AllProfiles": "Tous les profils",
        "ProfileLibrary_BuiltInOnly": "Intégré uniquement",
        "ProfileLibrary_CustomOnly": "Personnalisé uniquement",
        "ProfileLibrary_Melee": "Combat rapproché",
        "ProfileLibrary_Ranged": "À distance",
        "ProfileLibrary_Mage": "Mage",
        "ProfileLibrary_Support": "Support",
        "ProfileLibrary_CountLabel": "{0} profils",
        "ProfileLibrary_LoadBtn": "Charger",
        "ProfileLibrary_ExportBtn": "Exporter",
        "ProfileLibrary_ShareBtn": "↑ PARTAGER",
        "ProfileLibrary_DeleteBtn": "Supprimer",
        "ProfileLibrary_StatusText": "",
        "ProfileLibrary_NewProfileBtn": "Nouveau profil",
        "ProfileLibrary_ImportBtn": "Importer",
        "ProfileLibrary_ShareCodePlaceholder": "Entrez un code de partage (ex. GX-A3F9) et cliquez sur ↓ Télécharger",
        "ProfileLibrary_DownloadBtn": "↓ Télécharger",
        "ProfileWizard_Title": "Assistant",
        "ProfileWizard_Header": "ASSISTANT DE PROFIL",
        "ProfileWizard_NameLabel": "NOM DU PROFIL",
        "ProfileWizard_ClassLabel": "CLASSE",
        "ProfileWizard_Melee": "Combat rapproché",
        "ProfileWizard_Mage": "Mage",
        "ProfileWizard_Ranged": "À distance",
        "ProfileWizard_Support": "Support",
        "ProfileWizard_CombatEngines": "MOTEURS DE COMBAT",
        "ProfileWizard_EnableAutoTarget": "Activer la cible automatique",
        "ProfileWizard_EnableKiteEngine": "Activer le moteur Kite",
        "ProfileWizard_EnableMageSystem": "Activer le système Mage",
        "ProfileWizard_EnableSupportMode": "Activer le mode Support",
        "ProfileWizard_QuickKeys": "RACCOURCIS",
        "ProfileWizard_AButton": "A:",
        "ProfileWizard_BButton": "B:",
        "ProfileWizard_XButton": "X:",
        "ProfileWizard_YButton": "Y:",
        "ProfileWizard_Review": "RÉVISION",
        "ProfileWizard_ReviewMessage": "Le profil sera créé avec des paramètres de mouvement par défaut. Vous pouvez tout ajuster plus tard.",
        "ProfileWizard_BackBtn": "RETOUR",
        "ProfileWizard_NextBtn": "SUIVANT",
        "RadialMenu_Title": "Menu radial",
        "RadialMenu_SelectItemText": "SÉLECTIONNER UN ÉLÉMENT",
        "RadialMenu_SelectItemTooltip": "Sélectionnez une action dans le menu radial",
        "RadialMenu_ExecuteText": "Relâchez les déclencheurs pour utiliser",
        "RadialMenu_ExecuteTooltip": "Exécuter l'action sélectionnée",
        "RadialSetup_Title": "Configuration du menu radial",
        "RadialSetup_Header": "CONFIGURATION DU MENU RADIAL",
        "RadialSetup_Hint": "Déclencheur : Maintenez LT + RT simultanément → Visez la manette droite → Relâchez les déclencheurs pour exécuter.",
        "RadialSetup_Column_DisplayName": "NOM D'AFFICHAGE",
        "RadialSetup_Column_CommandChat": "COMMANDE / CHAT",
        "RadialSetup_Column_KeyBinding": "RACCOURCI CLAVIER",
        "RadialSetup_Column_Emotes": "ÉMOTES",
        "RadialSetup_FooterHint": "Laissez vide pour désactiver un slot. 8 Slots = 8 directions.",
        "RadialSetup_SaveBtn": "ENREGISTRER RADIAL",
        "RadialMenuGallery_Title": "SÉLECTIONNER UNE ÉMOTE",
        "RadialMenuGallery_CloseBtn": "✕",
        "RadialMenuGallery_EmoteStatus": "Fallback Emoji activé",
        "RadialMenuGallery_DownloadBtn": "⬇ Télécharger depuis iROWiki",
        "AdminWarning_Message": "Exécution non en tant qu'administrateur — SendInput peut ne pas fonctionner correctement.",
        "Btn_RestartAsAdmin": "↑ Redémarrer en tant qu'admin",
        "Btn_RestartAsAdmin_Tooltip": "Redémarrer l'application en tant qu'administrateur",
        "ClassBadge_Empty": "⚔ –",
        "GameMode_PreRenewal": "AVANT-RENOUVELLEMENT",
        "GameMode_Renewal": "RENOUVELLEMENT",
        "ControllerName_NoController": "Aucun contrôleur",
        "BatteryLevel_Empty": "–",
        "SettingsWindow_Title": "Paramètres",
        "SettingsWindow_Header": "PARAMÈTRES GÉNÉRAUX",
        "Btn_Close_Tooltip": "Fermer la fenêtre de paramètres",
        "Settings_AutoStart": "Démarrer automatiquement le moteur au lancement",
        "Settings_AutoStart_Tooltip": "Activer automatiquement le moteur au démarrage du client",
        "Settings_Sound": "Activer le feedback sonore",
        "Settings_Sound_Tooltip": "Activer les sons de clic et de compétence",
        "Settings_Rumble": "Activer la vibration du contrôleur",
        "Settings_Rumble_Tooltip": "Activer la vibration du contrôleur pour le feedback",
        "Settings_MiniMode": "Démarrer en mode Mini",
        "Settings_MiniMode_Tooltip": "Démarrer l'app en mode mini-overlay (compact)",
        "Settings_FocusLock": "Mettre en pause le moteur lorsque RO est en arrière-plan",
        "Settings_FocusLock_Tooltip": "Mettre en pause le moteur lorsque RO est en arrière-plan",
        "Settings_FocusLock_Description": "Empêche les entrées accidentelles dans Discord ou navigateur lorsque l'onglet est quitté.",
        "Settings_KernelInput": "Utiliser l'entrée matérielle (contournement Anti-Cheat)",
        "Settings_KernelInput_Tooltip": "Nécessite le pilote Interception. Contourne les blocages Gepard/Harmony.",
        "Btn_InstallDriver": "Installer le pilote",
        "Btn_InstallDriver_Tooltip": "Installe le pilote kernel requis (redémarrage requis)",
        "Settings_LogLevel_Label": "NIVEAU DE LOG",
        "LogLevel_Debug": "Debug",
        "LogLevel_Info": "Info",
        "LogLevel_Warning": "Avertissement",
        "LogLevel_Error": "Erreur",
        "Btn_ReportBug": "🐛 Signaler un bug / Demander une fonctionnalité",
        "Btn_ReportBug_Tooltip": "Ouvre la page GitHub Issues dans votre navigateur web",
        "Lbl_Version_Tooltip": "Version actuelle de l'application",
        "Lbl_SettingsPath_Tooltip": "Ouvrir le répertoire des paramètres (Explorateur Windows)",
        "Btn_Reset": "RÉINITIALISER AUX PARAMÈTRES PAR DÉFAUT",
        "Btn_Reset_Tooltip": "Réinitialiser tous les paramètres aux valeurs par défaut",
        "Btn_SaveAndClose": "ENREGISTRER & FERMER",
        "Btn_SaveAndClose_Tooltip": "Enregistrer les paramètres et fermer la fenêtre",
        "Window_Remap_Title": "Réaffectation des boutons",
        "Window_Remap_Header": "RÉAFFECTATION DES BOUTONS",
        "Layer_Title_1": "COUCHE 1",
        "Layer_Title_2": "COUCHE 2",
        "Layer_Title_3": "COUCHE 3",
        "Layer_Title_4": "COUCHE 4",
        "Layer_Title_5": "COUCHE 5",
        "Window_Combo_Title": "Éditeur de combinaison",
        "Window_Combo_Header": "ÉDITEUR MOTEUR COMBINAISON",
        "Combo_Slot_Label_1": "SLOT 1",
        "Combo_Slot_Label_2": "SLOT 2",
        "Combo_Slot_Label_3": "SLOT 3",
        "Combo_Slot_Label_4": "SLOT 4",
        "Combo_Slot_Label_5": "SLOT 5",
        "Window_Community_Title": "Navigateur communautaire",
        "Window_Community_Header": "NAVIGATEUR COMMUNAUTAIRE",
        "Search_Community_Placement": "Rechercher des profils...",
        "Community_NoResults": "Aucun profil correspondant trouvé",
        "Btn_LoadMore": "CHARGER PLUS",
        "Btn_LoadMore_Tooltip": "Charger plus de profils communautaires",
        "Btn_Close_Community": "FERMER COMMUNAUTÉ",
        "Btn_Close_Community_Tooltip": "Fermer le navigateur communautaire",
        "Window_DaisyWheel_Title": "Daisy Wheel",
        "Window_DaisyWheel_Header": "DAISY WHEEL",
        "Window_Handheld_Title": "Mode handheld",
        "Window_Handheld_Header": "MODE HANDHELD",
        "Window_Overlay_Title": "Overlay en jeu",
        "Window_Overlay_Header": "OVERLAY EN JEU",
        "Btn_ToggleHUD": "BASCULER HUD",
        "Btn_ToggleHUD_Tooltip": "Afficher/masquer l'overlay HUD en jeu",
        "Window_Macro_Title": "Éditeur de macro",
        "Window_Macro_Header": "ÉDITEUR DE MACRO",
        "Window_MacroRecorder_Title": "Enregistreur de macro",
        "Window_MacroRecorder_Header": "ENREGISTREUR DE MACRO",
        "Btn_StartRecording": "DÉMARRER L'ENREGISTREMENT",
        "Btn_StartRecording_Tooltip": "Démarrer l'enregistrement des actions de macro",
        "Btn_StopRecording": "ARRÊTER L'ENREGISTREMENT",
        "Btn_StopRecording_Tooltip": "Arrêter l'enregistrement et enregistrer la macro",
        "Window_Timeline_Title": "Chronologie de macro",
        "Window_Timeline_Header": "CHRONOLOGIE DE MACRO",
        "Window_Library_Title": "Bibliothèque de profils",
        "Window_Library_Header": "BIBLIOTHÈQUE DE PROFILS",
        "Window_Wizard_Title": "Assistant",
        "Window_Wizard_Header": "ASSISTANT DE PROFIL",
        "Btn_Next": "SUIVANT",
        "Btn_Next_Tooltip": "Passer à l'étape suivante",
        "Btn_Back": "PRÉCÉDENT",
        "Btn_Back_Tooltip": "Retourner à l'étape précédente",
        "Btn_Finish": "TERMINER",
        "Btn_Finish_Tooltip": "Terminer la création du profil",
        "Window_Radial_Title": "Configuration du menu radial",
        "Window_Radial_Header": "CONFIGURATION DU MENU RADIAL",
        "Splash_Loading": "Chargement...",
        "Splash_Version": "Version {version}",
    }
    
    return translations.get(key, value)

# Generate all language files
for lang_code, lang_name in sorted(LANGUAGES.items()):
    if lang_code == "en":
        continue  # Skip English
    
    print(f"Processing: {lang_name} ({lang_code})")
    
    # Create translation dictionary
    trans_dict = {}
    for key, value in en_keys.items():
        # Use appropriate translation function or fallback to English
        if lang_code == "de":
            translated = translate_de(value)
        elif lang_code == "fr":
            translated = translate_fr(value)
        else:
            # For other languages, use English as placeholder
            translated = value
        
        trans_dict[key] = translated
    
    # Write to file
    filename = f"{lang_code}.json"
    filepath = os.path.join(PROJECT_ROOT, filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(trans_dict, f, indent=2, ensure_ascii=False)
        f.write('\n')
    
    print(f"  ✓ Created: {filename}")

print()
print("=" * 70)
print("LANGUAGE FILE GENERATION COMPLETE!")
print(f"Total language files created: {len(LANGUAGES) - 1}")
print("=" * 70)
